/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface AccessControlInterface extends utils.Interface {
  functions: {
    "MAX_REVOKED_CREDENTIALS()": FunctionFragment;
    "emergencyTransferLockOwnership(uint256,address)": FunctionFragment;
    "getLockInfo(uint256)": FunctionFragment;
    "getLockOwner(uint256)": FunctionFragment;
    "getRevokedSignatureCount(uint256)": FunctionFragment;
    "getRevokedSignatures(uint256,bytes32[])": FunctionFragment;
    "getSignerAddress(uint256)": FunctionFragment;
    "getTotalLocks()": FunctionFragment;
    "isCredentialRevoked(uint256,bytes32)": FunctionFragment;
    "lockExistsView(uint256)": FunctionFragment;
    "locks(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "registerLock(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeCredential(uint256,bytes32,bytes)": FunctionFragment;
    "revokedCredentials(uint256,bytes32)": FunctionFragment;
    "transferLockOwnership(uint256,bytes32,bytes,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "verifySignerAddress(uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_REVOKED_CREDENTIALS"
      | "emergencyTransferLockOwnership"
      | "getLockInfo"
      | "getLockOwner"
      | "getRevokedSignatureCount"
      | "getRevokedSignatures"
      | "getSignerAddress"
      | "getTotalLocks"
      | "isCredentialRevoked"
      | "lockExistsView"
      | "locks"
      | "owner"
      | "pause"
      | "paused"
      | "registerLock"
      | "renounceOwnership"
      | "revokeCredential"
      | "revokedCredentials"
      | "transferLockOwnership"
      | "transferOwnership"
      | "unpause"
      | "verifySignerAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_REVOKED_CREDENTIALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyTransferLockOwnership",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockInfo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLockOwner",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevokedSignatureCount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevokedSignatures",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignerAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalLocks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isCredentialRevoked",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "lockExistsView",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "locks",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerLock",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokedCredentials",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferLockOwnership",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifySignerAddress",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_REVOKED_CREDENTIALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyTransferLockOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevokedSignatureCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevokedSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalLocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCredentialRevoked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockExistsView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "locks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokedCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferLockOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySignerAddress",
    data: BytesLike
  ): Result;

  events: {
    "CredentialRevoked(uint256,bytes32,address)": EventFragment;
    "LockOwnershipTransferred(uint256,address,address)": EventFragment;
    "LockRegistered(uint256,address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CredentialRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LockOwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LockRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface CredentialRevokedEventObject {
  lockId: BigNumber;
  vcHash: string;
  owner: string;
}
export type CredentialRevokedEvent = TypedEvent<
  [BigNumber, string, string],
  CredentialRevokedEventObject
>;

export type CredentialRevokedEventFilter =
  TypedEventFilter<CredentialRevokedEvent>;

export interface LockOwnershipTransferredEventObject {
  lockId: BigNumber;
  previousOwner: string;
  newOwner: string;
}
export type LockOwnershipTransferredEvent = TypedEvent<
  [BigNumber, string, string],
  LockOwnershipTransferredEventObject
>;

export type LockOwnershipTransferredEventFilter =
  TypedEventFilter<LockOwnershipTransferredEvent>;

export interface LockRegisteredEventObject {
  lockId: BigNumber;
  owner: string;
  signerAddress: string;
}
export type LockRegisteredEvent = TypedEvent<
  [BigNumber, string, string],
  LockRegisteredEventObject
>;

export type LockRegisteredEventFilter = TypedEventFilter<LockRegisteredEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface AccessControl extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AccessControlInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_REVOKED_CREDENTIALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    emergencyTransferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getLockInfo(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean] & {
        owner: string;
        signerAddress: string;
        revokedCount: BigNumber;
        exists: boolean;
      }
    >;

    getLockOwner(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRevokedSignatureCount(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRevokedSignatures(
      lockId: PromiseOrValue<BigNumberish>,
      vcHashes: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[boolean[]]>;

    getSignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTotalLocks(overrides?: CallOverrides): Promise<[BigNumber]>;

    isCredentialRevoked(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lockExistsView(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    locks(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean] & {
        owner: string;
        signerAddress: string;
        revokedCount: BigNumber;
        exists: boolean;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    registerLock(
      signerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeCredential(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokedCredentials(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifySignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      signerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  MAX_REVOKED_CREDENTIALS(overrides?: CallOverrides): Promise<BigNumber>;

  emergencyTransferLockOwnership(
    lockId: PromiseOrValue<BigNumberish>,
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getLockInfo(
    lockId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, boolean] & {
      owner: string;
      signerAddress: string;
      revokedCount: BigNumber;
      exists: boolean;
    }
  >;

  getLockOwner(
    lockId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getRevokedSignatureCount(
    lockId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRevokedSignatures(
    lockId: PromiseOrValue<BigNumberish>,
    vcHashes: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<boolean[]>;

  getSignerAddress(
    lockId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getTotalLocks(overrides?: CallOverrides): Promise<BigNumber>;

  isCredentialRevoked(
    lockId: PromiseOrValue<BigNumberish>,
    vcHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lockExistsView(
    lockId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  locks(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, boolean] & {
      owner: string;
      signerAddress: string;
      revokedCount: BigNumber;
      exists: boolean;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  registerLock(
    signerAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeCredential(
    lockId: PromiseOrValue<BigNumberish>,
    vcHash: PromiseOrValue<BytesLike>,
    authSignature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokedCredentials(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferLockOwnership(
    lockId: PromiseOrValue<BigNumberish>,
    message: PromiseOrValue<BytesLike>,
    authSignature: PromiseOrValue<BytesLike>,
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifySignerAddress(
    lockId: PromiseOrValue<BigNumberish>,
    signerAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    MAX_REVOKED_CREDENTIALS(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyTransferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getLockInfo(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean] & {
        owner: string;
        signerAddress: string;
        revokedCount: BigNumber;
        exists: boolean;
      }
    >;

    getLockOwner(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getRevokedSignatureCount(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRevokedSignatures(
      lockId: PromiseOrValue<BigNumberish>,
      vcHashes: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<boolean[]>;

    getSignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getTotalLocks(overrides?: CallOverrides): Promise<BigNumber>;

    isCredentialRevoked(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lockExistsView(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    locks(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean] & {
        owner: string;
        signerAddress: string;
        revokedCount: BigNumber;
        exists: boolean;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    registerLock(
      signerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revokeCredential(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokedCredentials(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    verifySignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      signerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "CredentialRevoked(uint256,bytes32,address)"(
      lockId?: PromiseOrValue<BigNumberish> | null,
      vcHash?: PromiseOrValue<BytesLike> | null,
      owner?: null
    ): CredentialRevokedEventFilter;
    CredentialRevoked(
      lockId?: PromiseOrValue<BigNumberish> | null,
      vcHash?: PromiseOrValue<BytesLike> | null,
      owner?: null
    ): CredentialRevokedEventFilter;

    "LockOwnershipTransferred(uint256,address,address)"(
      lockId?: PromiseOrValue<BigNumberish> | null,
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): LockOwnershipTransferredEventFilter;
    LockOwnershipTransferred(
      lockId?: PromiseOrValue<BigNumberish> | null,
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): LockOwnershipTransferredEventFilter;

    "LockRegistered(uint256,address,address)"(
      lockId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      signerAddress?: PromiseOrValue<string> | null
    ): LockRegisteredEventFilter;
    LockRegistered(
      lockId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      signerAddress?: PromiseOrValue<string> | null
    ): LockRegisteredEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    MAX_REVOKED_CREDENTIALS(overrides?: CallOverrides): Promise<BigNumber>;

    emergencyTransferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getLockInfo(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLockOwner(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRevokedSignatureCount(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRevokedSignatures(
      lockId: PromiseOrValue<BigNumberish>,
      vcHashes: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalLocks(overrides?: CallOverrides): Promise<BigNumber>;

    isCredentialRevoked(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockExistsView(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    locks(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    registerLock(
      signerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeCredential(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokedCredentials(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifySignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      signerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_REVOKED_CREDENTIALS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    emergencyTransferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getLockInfo(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLockOwner(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRevokedSignatureCount(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRevokedSignatures(
      lockId: PromiseOrValue<BigNumberish>,
      vcHashes: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalLocks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isCredentialRevoked(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockExistsView(
      lockId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    locks(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerLock(
      signerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeCredential(
      lockId: PromiseOrValue<BigNumberish>,
      vcHash: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokedCredentials(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferLockOwnership(
      lockId: PromiseOrValue<BigNumberish>,
      message: PromiseOrValue<BytesLike>,
      authSignature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifySignerAddress(
      lockId: PromiseOrValue<BigNumberish>,
      signerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
